# Generated by Django 5.0.6 on 2024-07-19 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=30)),
                ('degree', models.CharField(max_length=30)),
                ('field', models.CharField(max_length=30)),
                ('fromDate', models.DateTimeField(auto_now_add=True)),
                ('toDate', models.DateTimeField()),
                ('description', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('company', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('fromDate', models.DateTimeField(auto_now_add=True)),
                ('toDate', models.DateTimeField()),
                ('description', models.DateTimeField()),
            ],
        ),
    ]
