# Generated by Django 5.0.6 on 2024-07-19 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_education_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(default='user-account.jpg', upload_to='profile_picture'),
        ),
    ]
