# Generated by Django 5.0.6 on 2024-07-26 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_userprofile_picture'),
        ('blog', '0003_comment_author_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='dislike',
            field=models.ManyToManyField(related_name='comment_dislike', to='account.userprofile'),
        ),
        migrations.AddField(
            model_name='comment',
            name='like',
            field=models.ManyToManyField(related_name='comment_like', to='account.userprofile'),
        ),
        migrations.AddField(
            model_name='post',
            name='dislike',
            field=models.ManyToManyField(related_name='post_dislike', to='account.userprofile'),
        ),
        migrations.AddField(
            model_name='post',
            name='like',
            field=models.ManyToManyField(related_name='post_like', to='account.userprofile'),
        ),
    ]
