# Generated by Django 5.0.6 on 2024-07-26 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_userprofile_picture'),
        ('blog', '0004_comment_dislike_comment_like_post_dislike_post_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='dislike',
            field=models.ManyToManyField(blank=True, null=True, related_name='comment_dislike', to='account.userprofile'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='like',
            field=models.ManyToManyField(blank=True, null=True, related_name='comment_like', to='account.userprofile'),
        ),
        migrations.AlterField(
            model_name='post',
            name='dislike',
            field=models.ManyToManyField(blank=True, null=True, related_name='post_dislike', to='account.userprofile'),
        ),
        migrations.AlterField(
            model_name='post',
            name='like',
            field=models.ManyToManyField(blank=True, null=True, related_name='post_like', to='account.userprofile'),
        ),
    ]
